// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Apprentice":return img`
................
.........88.....
........88.8....
.......888......
......88888.....
......88888.....
.....8888888....
.....8888888....
.....5555555....
....888888888...
......dfdfd.....
......dfdfd.....
......ddddd.....
.......888......
......88888.....
......88588.....
.....8885888....
.....8555558....
.....8855588....
....885585588...
....885888588...
...88888888888..
...88888888888..
.......f.f......
.......f.f......
.......f.f......
.......f.f......
......ff.ff.....
................
................
`;
            case "image2":
            case "dashEmpty":return img`
f f f f f f f f f f f f f f f f f f 
f . . . . . . . . . . . . . . . . f 
f . . . . . . . . . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image3":
            case "dashOne":return img`
f f f f f f f f f f f f f f f f f f 
f 2 2 2 2 . . . . . . . . . . . . f 
f 2 2 2 2 . . . . . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image4":
            case "dashTwo":return img`
f f f f f f f f f f f f f f f f f f 
f 4 4 4 4 4 4 4 4 . . . . . . . . f 
f 4 4 4 4 4 4 4 4 . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image5":
            case "dashThree":return img`
f f f f f f f f f f f f f f f f f f 
f 5 5 5 5 5 5 5 5 5 5 5 5 . . . . f 
f 5 5 5 5 5 5 5 5 5 5 5 5 . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image6":
            case "dashFour":return img`
f f f f f f f f f f f f f f f f f f 
f 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 f 
f 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 f 
f f f f f f f f f f f f f f f f f f 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
