// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "dashEmpty":return img`
f f f f f f f f f f f f f f f f f f 
f . . . . . . . . . . . . . . . . f 
f . . . . . . . . . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image3":
            case "dashOne":return img`
f f f f f f f f f f f f f f f f f f 
f 2 2 2 2 . . . . . . . . . . . . f 
f 2 2 2 2 . . . . . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image4":
            case "dashTwo":return img`
f f f f f f f f f f f f f f f f f f 
f 4 4 4 4 4 4 4 4 . . . . . . . . f 
f 4 4 4 4 4 4 4 4 . . . . . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image5":
            case "dashThree":return img`
f f f f f f f f f f f f f f f f f f 
f 5 5 5 5 5 5 5 5 5 5 5 5 . . . . f 
f 5 5 5 5 5 5 5 5 5 5 5 5 . . . . f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image6":
            case "dashFour":return img`
f f f f f f f f f f f f f f f f f f 
f 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 f 
f 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 f 
f f f f f f f f f f f f f f f f f f 
`;
            case "image1":
            case "Apprentice":return img`
. . . . . . . . f . . . . . . . 
. . . . . . . f 8 f . . . . . . 
. . . . . . f f 8 f . . . . . . 
. . . . . f f 8 8 9 f . . . . . 
. . . . . f f 8 8 9 f . . . . . 
. . . . f f 8 8 8 8 9 f . . . . 
. . . . f 4 4 5 5 1 1 f . . . . 
. . . f f f f 8 8 8 8 9 f . . . 
. . . . f d f d d f d f . . . . 
. . . . f 3 3 d d 3 3 f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . f f 8 8 9 f . . . . . 
. . . . f f 8 4 1 8 9 f . . . . 
. . . . f f 8 4 5 8 9 f . . . . 
. . . . f f f f f f f f . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image7":
            case "uwherg":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "ierw":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image11":
            case "oweifhgvwo":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image12":
            case "ApprenticeFaceRight2":return img`
. . . . . f f f . . . . . . . . 
. . . . f f f 8 f . . . . . . . 
. . . . f f 8 8 9 f . . . . . . 
. . . f . f 8 8 8 9 f . . . . . 
. . . . . f 8 8 8 9 f . . . . . 
. . . . f f 8 8 8 8 9 f . . . . 
. . . . f 4 4 5 5 1 1 f . . . . 
. . . f f 8 8 8 8 8 9 9 f . . . 
. . . . f f d d d f d f . . . . 
. . . . . f d d 3 3 d f . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f 8 9 f . . . . . 
. . . . . f f 8 8 8 5 f . . . . 
. . . . . f f 8 8 8 4 f f . . . 
. . . . . f f f f f f f f . . . 
. . . . . . . f f . . . . . . . 
`;
            case "image8":
            case "ApprenticeFaceRight1":return img`
. . . . . f f f . . . . . . . . 
. . . . f f f 8 f . . . . . . . 
. . . . f f 8 8 9 f . . . . . . 
. . . f . f 8 8 8 9 f . . . . . 
. . . . . f 8 8 8 9 f . . . . . 
. . . . f f 8 8 8 8 9 f . . . . 
. . . . f 4 4 5 5 1 1 f . . . . 
. . . f f 8 8 8 8 8 9 9 f . . . 
. . . . f f d d d f d f . . . . 
. . . . . f d d 3 3 d f . . . . 
. . . . . . f f f f f . . . . . 
. . . . . . f f 8 9 f . . . . . 
. . . . . f f 8 8 8 5 f . . . . 
. . . . . f f 8 8 8 4 f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . f f . . . . . . . 
`;
            case "image9":
            case "ApprenticeFaceLeft1":return img`
. . . . . . . . f f f . . . . . 
. . . . . . . f 8 9 9 f . . . . 
. . . . . . f f 8 8 9 f . . . . 
. . . . . f f 8 8 8 f . f . . . 
. . . . . f f 8 8 8 f . . . . . 
. . . . f f 8 8 8 8 9 f . . . . 
. . . . f 4 4 5 5 1 1 f . . . . 
. . . f f f 8 8 8 8 8 9 f . . . 
. . . . f d f d d d f f . . . . 
. . . . f d 3 3 d d f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f 8 9 f . . . . . . 
. . . . f 5 8 8 8 9 f . . . . . 
. . . . f 4 8 8 8 9 f . . . . . 
. . . . f f f f f f f . . . . . 
. . . . . . . f f . . . . . . . 
`;
            case "image13":
            case "ApprenticeFaceLeft2":return img`
. . . . . . . . f f f . . . . . 
. . . . . . . f 8 9 9 f . . . . 
. . . . . . f f 8 8 9 f . . . . 
. . . . . f f 8 8 8 f . f . . . 
. . . . . f f 8 8 8 f . . . . . 
. . . . f f 8 8 8 8 9 f . . . . 
. . . . f 4 4 5 5 1 1 f . . . . 
. . . f f f 8 8 8 8 8 9 f . . . 
. . . . f d f d d d f f . . . . 
. . . . f d 3 3 d d f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . f f 8 9 f . . . . . . 
. . . . f 5 8 8 8 9 f . . . . . 
. . . f f 4 8 8 8 9 f . . . . . 
. . . f f f f f f f f . . . . . 
. . . . . . . f f . . . . . . . 
`;
            case "image19":
            case "health6":return img`
.ff.ff...ff.ff...ff.ff...ff.ff...ff.ff...ff.ff.
f22f21f.f22f21f.f22f21f.f22f21f.f22f21f.f22f21f
f22222f.f22222f.f22222f.f22222f.f22222f.f22222f
fc2222f.fc2222f.fc2222f.fc2222f.fc2222f.fc2222f
.fc22f...fc22f...fc22f...fc22f...fc22f...fc22f.
..fcf.....fcf.....fcf.....fcf.....fcf.....fcf..
...f.......f.......f.......f.......f.......f...
`;
            case "image18":
            case "health5":return img`
. f f . f f . . . f f . f f . . . f f . f f . . . f f . f f . . . f f . f f . 
f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f 
f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f 
f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f 
. f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . 
. . f c f . . . . . f c f . . . . . f c f . . . . . f c f . . . . . f c f . . 
. . . f . . . . . . . f . . . . . . . f . . . . . . . f . . . . . . . f . . . 
`;
            case "image17":
            case "health4":return img`
. f f . f f . . . f f . f f . . . f f . f f . . . f f . f f . 
f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f 
f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f 
f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f 
. f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . 
. . f c f . . . . . f c f . . . . . f c f . . . . . f c f . . 
. . . f . . . . . . . f . . . . . . . f . . . . . . . f . . . 
`;
            case "image16":
            case "health3":return img`
. f f . f f . . . f f . f f . . . f f . f f . 
f 2 2 f 2 1 f . f 2 2 f 2 1 f . f 2 2 f 2 1 f 
f 2 2 2 2 2 f . f 2 2 2 2 2 f . f 2 2 2 2 2 f 
f c 2 2 2 2 f . f c 2 2 2 2 f . f c 2 2 2 2 f 
. f c 2 2 f . . . f c 2 2 f . . . f c 2 2 f . 
. . f c f . . . . . f c f . . . . . f c f . . 
. . . f . . . . . . . f . . . . . . . f . . . 
`;
            case "image15":
            case "health2":return img`
. f f . f f . . . f f . f f . 
f 2 2 f 2 1 f . f 2 2 f 2 1 f 
f 2 2 2 2 2 f . f 2 2 2 2 2 f 
f c 2 2 2 2 f . f c 2 2 2 2 f 
. f c 2 2 f . . . f c 2 2 f . 
. . f c f . . . . . f c f . . 
. . . f . . . . . . . f . . . 
`;
            case "image14":
            case "health1":return img`
. f f . f f . 
f 2 2 f 2 1 f 
f 2 2 2 2 2 f 
f c 2 2 2 2 f 
. f c 2 2 f . 
. . f c f . . 
. . . f . . . 
`;
            case "image20":
            case "slimeEnemy":return img`
. . . . f f f f f f . . . . 
. . . f 7 7 1 1 7 1 f . . . 
. . f 7 6 6 6 6 6 6 1 f . . 
. . f 7 6 7 7 7 7 6 7 f . . 
. f 7 6 7 7 7 7 7 7 6 1 f . 
. f 7 6 f 7 7 7 7 f 6 1 f . 
. f 7 6 f 7 7 7 7 f 6 7 f . 
f 7 6 7 f 7 7 7 7 f 7 6 1 f 
f 7 6 3 3 7 7 7 7 3 3 6 7 f 
f 7 6 7 7 7 7 7 7 7 7 6 7 f 
. f f f f f f f f f f f f . 
`;
            case "image21":
            case "bookEnemy":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . f f f 3 3 f f . . . . 
. f f f f 3 3 2 2 2 f e f . . . 
f 2 2 2 2 2 2 2 2 2 f f e f . . 
f 2 2 2 2 2 2 2 e f f d f e f . 
f 2 2 2 2 2 2 e f 1 d 1 d f e f 
f e e e e e e f d 1 d 1 1 f f f 
f e e e f f f f d 1 d 1 1 1 1 f 
f f f f 1 1 d d 1 1 1 1 f f 1 f 
. . . . f f f f 1 f f 1 f . f . 
. . . . . . . . f . . f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image22":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image25":
            case "Projectile3":return img`
. . . . . . 6 6 . . . . . . 
. . . . . 6 9 9 6 . . . . . 
. . . . 6 9 f f 9 6 . . . . 
. . 6 6 9 f 1 1 f 9 6 6 . . 
. 6 9 9 9 f 5 1 f 9 9 9 6 . 
6 9 f f f 5 5 5 1 f f f 9 6 
6 9 f 4 5 5 5 5 5 5 1 f 9 6 
. 6 9 f 4 5 5 5 5 1 f 9 6 . 
. . 6 9 f 4 5 5 5 f 9 6 . . 
. 6 9 f 4 5 f f 5 1 f 9 6 . 
6 9 f 4 5 f 9 9 f 5 1 f 9 6 
. 6 9 f f 9 6 6 9 f f 9 6 . 
. . 6 9 9 6 . . 6 9 9 6 . . 
. . . 6 6 . . . . 6 6 . . . 
`;
            case "image23":
            case "Projectile1":return img`
. . . . . . . . . . . . . . 
. . . . . . . . . . . . . . 
. . . . . . f f . . . . . . 
. . . . . f 1 1 f . . . . . 
. . . . . f 5 1 f . . . . . 
. . f f f 5 5 5 1 f f f . . 
. . f 4 5 5 5 5 5 5 1 f . . 
. . . f 4 5 5 5 5 1 f . . . 
. . . . f 4 5 5 5 f . . . . 
. . . f 4 5 f f 5 1 f . . . 
. . f 4 5 f . . f 5 1 f . . 
. . . f f . . . . f f . . . 
. . . . . . . . . . . . . . 
. . . . . . . . . . . . . . 
`;
            case "image24":
            case "Projectile2":return img`
. . . . . . . . . . . . . . 
. . . . . . 9 9 . . . . . . 
. . . . . 9 f f 9 . . . . . 
. . . . 9 f 1 1 f 9 . . . . 
. . 9 9 9 f 5 1 f 9 9 9 . . 
. 9 f f f 5 5 5 1 f f f 9 . 
. 9 f 4 5 5 5 5 5 5 1 f 9 . 
. . 9 f 4 5 5 5 5 1 f 9 . . 
. . . 9 f 4 5 5 5 f 9 . . . 
. . 9 f 4 5 f f 5 1 f 9 . . 
. 9 f 4 5 f 9 9 f 5 1 f 9 . 
. . 9 f f 9 . . 9 f f 9 . . 
. . . 9 9 . . . . 9 9 . . . 
. . . . . . . . . . . . . . 
`;
            case "image26":
            case "Projectile4right":return img`
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . 9 6 6 f f . . . . 
. . . . . . 6 6 9 9 9 9 9 f 1 1 f . . . 
. . . 9 9 9 9 9 9 9 6 6 6 f 5 1 f . . . 
. . . . 6 6 6 6 9 9 f f f 5 5 5 1 f f f 
. . 9 9 9 9 9 9 6 6 f 4 5 5 5 5 5 5 1 f 
. . . . 6 6 6 9 9 9 9 f 4 5 5 5 5 1 f . 
. . 9 9 9 9 9 6 6 6 6 6 f 4 5 5 5 f . . 
. . . 6 6 6 9 9 9 6 6 f 4 5 f f 5 1 f . 
. . . . . . . 6 6 9 f 4 5 f 6 9 f 5 1 f 
. 6 6 6 6 9 9 9 9 9 9 f f . 9 6 6 f f . 
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
`;
            case "image27":
            case "Projectile4left":return img`
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
. . . . f f 6 6 9 . . . . . . . . . . . 
. . . f 1 1 f 9 9 9 9 9 6 6 . . . . . . 
. . . f 1 5 f 6 6 6 9 9 9 9 9 9 9 . . . 
f f f 1 5 5 5 f f f 9 9 6 6 6 6 . . . . 
f 1 5 5 5 5 5 5 4 f 6 6 9 9 9 9 9 9 . . 
. f 1 5 5 5 5 4 f 9 9 9 9 6 6 6 . . . . 
. . f 5 5 5 4 f 6 6 6 6 6 9 9 9 9 9 . . 
. f 1 5 f f 5 4 f 6 6 9 9 9 6 6 6 . . . 
f 1 5 f 9 6 f 5 4 f 9 6 6 . . . . . . . 
. f f 6 6 9 . f f 9 9 9 9 9 9 6 6 6 6 . 
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . . . . 
`;
            case "image32":
            case "manaMeterFour":return img`
..................
..................
..................
...ffffffffffff...
...f9999999999f...
..5f9f999999f9f...
..5f9ff9999ff9f...
.5159f9f99f9f9f...
..5f9f99ff99f9f...
..5f9f999999f9f...
...f9f999999f9f...
...f9f999999f9f...
...f9f999999f9f...
...f9999999999f5..
...f999ffff999f5..
...f99f9999f99515.
...f9f999999f51115
...f9f999999f9515.
...f9ffffffff9f5..
...f9f999999f9f5..
...f9f999999f9f5..
...f9f999999f9f5..
...f9999999999f...
...f9f999999f9f...
...f9ff99999f9f...
...f9f9f9999f9f...
...f9f99f999f9f...
...f9f999f99f9f...
...f9f9999f9f9f...
...f9f99999ff9f...
...f9f999999f9f...
...f5999999999f...
...5159ffff999f...
...f59f9999f99f...
...f9f999999f9f...
...f9f999999f9f...
...f9ffffffff9f...
...f9f999999f9f...
...f9f999999f9f...
...f9f999999f9f...
...f9999999999f...
...ffffffffffff...
..................
..................
..................
`;
            case "image28":
            case "manaMeterEmpty":return img`
..................
..................
..................
...ffffffffffff...
...f..........f...
...f.f......f.f...
...f.ff....ff.f...
...f.f.f..f.f.f...
...f.f..ff..f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...f...ffff...f...
...f..f....f..f...
...f.f......f.f...
...f.f......f.f...
...f.ffffffff.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...f.f......f.f...
...f.ff.....f.f...
...f.f.f....f.f...
...f.f..f...f.f...
...f.f...f..f.f...
...f.f....f.f.f...
...f.f.....ff.f...
...f.f......f.f...
...f..........f...
...f...ffff...f...
...f..f....f..f...
...f.f......f.f...
...f.f......f.f...
...f.ffffffff.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...ffffffffffff...
..................
..................
..................
`;
            case "image29":
            case "manaMeterOne":return img`
..................
..................
..................
...ffffffffffff...
...f..........f...
...f.f......f.f...
...f.ff....ff.f...
...f.f.f..f.f.f...
...f.f..ff..f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...f...ffff...f...
...f..f....f..f...
...f.f......f.f...
...f.f......f.f...
...f.ffffffff.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...f.f......f.f...
...f.ff.....f.f...
...f.f.f....f.f...
...f.f..f...f.f...
...f.f...f..f.f...
...f.f....f.f.f...
...f.f.....ff.f...
...f.f......f.f...
...fccccccccccf...
...fcccffffcccf...
...fccfccccfccf...
...fcfccccccfcf...
...fcfccccccfcf...
...fcffffffffcf...
...fcfccccccfcf...
...fcfccccccfcf...
...fcfccccccfcf...
...fccccccccccf...
...ffffffffffff...
..................
..................
..................
`;
            case "image30":
            case "manaMeterTwo":return img`
..................
..................
..................
...ffffffffffff...
...f..........f...
...f.f......f.f...
...f.ff....ff.f...
...f.f.f..f.f.f...
...f.f..ff..f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f..........f...
...f...ffff...f...
...f..f....f..f...
...f.f......f.f...
...f.f......f.f...
...f.ffffffff.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...faaaaaaaaaaf...
...fafaaaaaafaf...
...faffaaaaafaf...
...fafafaaaafaf...
...fafaafaaafaf...
...fafaaafaafaf...
...fafaaaafafaf...
...fafaaaaaffaf...
...fafaaaaaafaf...
...faaaaaaaaaaf...
...faaaffffaaaf...
...faafaaaafaaf...
...fafaaaaaafaf...
...fafaaaaaafaf...
...faffffffffaf...
...fafaaaaaafaf...
...fafaaaaaafaf...
...fafaaaaaafaf...
...faaaaaaaaaaf...
...ffffffffffff...
..................
..................
..................
`;
            case "image31":
            case "manaMeterThree":return img`
..................
..................
..................
...ffffffffffff...
...f..........f...
...f.f......f.f...
...f.ff....ff.f...
...f.f.f..f.f.f...
...f.f..ff..f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f.f......f.f...
...f8888888888f...
...f888ffff888f...
...f88f8888f88f...
...f8f888888f8f...
...f8f888888f8f...
...f8ffffffff8f...
...f8f888888f8f...
...f8f888888f8f...
...f8f888888f8f...
...f8888888888f...
...f8f888888f8f...
...f8ff88888f8f...
...f8f8f8888f8f...
...f8f88f888f8f...
...f8f888f88f8f...
...f8f8888f8f8f...
...f8f88888ff8f...
...f8f888888f8f...
...f8888888888f...
...f888ffff888f...
...f88f8888f88f...
...f8f888888f8f...
...f8f888888f8f...
...f8ffffffff8f...
...f8f888888f8f...
...f8f888888f8f...
...f8f888888f8f...
...f8888888888f...
...ffffffffffff...
..................
..................
..................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
